spring:
  #  配置视图解析器
  mvc:
    view:
      prefix: /
      suffix: .html

  datasource:
    url: jdbc:mysql://localhost:3306/ch?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #  控制台是否打印sql
    #show-sql: true


  # redis相关配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: root
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间
    timeout: 2000
  cache:
    type: redis


  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}




mybatis-plus:
  #  mybatis扫描mapper.xml文件的位置
  mapper-locations: classpath*:/mapper-xml/*.xml
  #  实体类扫描（实体类别名）
  type-aliases-package: com.ch.dto
  configuration:
    cache-enabled:

#  日志配置（SpringBoot 默认使用slf4j + logback日志框架）：
#  如果项目里要使用logback.xml来配置日志的话，直接在resourse下建一个logback-spring.xml,SpringBoot会自动识别该文件
#  此时在applicatiom.yml文件中配置的logging会被覆盖掉，SpringBoot会直接启用logback.xml的相关配置。

logging:
  #  com.ch.mapper包下的日志输出级别是debug级别
  level.com.ch.mapper: debug
  #  除去上面配置的包，其他包下的日志输出级别则是info级别
  level.root: info
  #  不配置path或者file，则不活生成对应的日志文件
  #path: e:/chLogs

#  pattern:
#    console: %d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n

cache:
  test:
    expire-time: 600
    name: test
  user:
    expire-time: 1800
    name: user
  default:
    expire-time: 1800